//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class CallLengthRepartition {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class ResponseTimeRepartition {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class action {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ereg", typeof(ereg))]
    [System.Xml.Serialization.XmlElementAttribute("exec", typeof(exec))]
    [System.Xml.Serialization.XmlElementAttribute("log", typeof(log))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class ereg {
    
    private string assign_toField;
    
    private eregCheck_it check_itField;
    
    private string headerField;
    
    private string regexpField;
    
    private eregSearch_in search_inField;
    
    public ereg() {
        this.check_itField = eregCheck_it.@false;
        this.search_inField = eregSearch_in.msg;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string assign_to {
        get {
            return this.assign_toField;
        }
        set {
            this.assign_toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(eregCheck_it.@false)]
    public eregCheck_it check_it {
        get {
            return this.check_itField;
        }
        set {
            this.check_itField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string regexp {
        get {
            return this.regexpField;
        }
        set {
            this.regexpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(eregSearch_in.msg)]
    public eregSearch_in search_in {
        get {
            return this.search_inField;
        }
        set {
            this.search_inField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
public enum eregCheck_it {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
public enum eregSearch_in {
    
    /// <remarks/>
    msg,
    
    /// <remarks/>
    hdr,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class exec {
    
    private string commandField;
    
    private execInt_cmd int_cmdField;
    
    private string play_pcapField;
    
    public exec() {
        this.int_cmdField = execInt_cmd.stop_call;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(execInt_cmd.stop_call)]
    public execInt_cmd int_cmd {
        get {
            return this.int_cmdField;
        }
        set {
            this.int_cmdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string play_pcap {
        get {
            return this.play_pcapField;
        }
        set {
            this.play_pcapField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
public enum execInt_cmd {
    
    /// <remarks/>
    stop_now,
    
    /// <remarks/>
    stop_gracefully,
    
    /// <remarks/>
    stop_call,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class log {
    
    private string messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class pause {
    
    private string millisecondsField;
    
    private string nextField;
    
    private string testField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string milliseconds {
        get {
            return this.millisecondsField;
        }
        set {
            this.millisecondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string next {
        get {
            return this.nextField;
        }
        set {
            this.nextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class recv {
    
    private object[] actionField;
    
    private string crlfField;
    
    private recvOptional optionalField;
    
    private bool optionalFieldSpecified;
    
    private string nextField;
    
    private string testField;
    
    private string responseField;
    
    private string requestField;
    
    private string lostField;
    
    private recvRtd rtdField;
    
    private bool rtdFieldSpecified;
    
    private recvRrs rrsField;
    
    private bool rrsFieldSpecified;
    
    private recvStart_rtd start_rtdField;
    
    private bool start_rtdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ereg", typeof(ereg), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("exec", typeof(exec), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("log", typeof(log), IsNullable=false)]
    public object[] action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string crlf {
        get {
            return this.crlfField;
        }
        set {
            this.crlfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public recvOptional optional {
        get {
            return this.optionalField;
        }
        set {
            this.optionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool optionalSpecified {
        get {
            return this.optionalFieldSpecified;
        }
        set {
            this.optionalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string next {
        get {
            return this.nextField;
        }
        set {
            this.nextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string request {
        get {
            return this.requestField;
        }
        set {
            this.requestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string lost {
        get {
            return this.lostField;
        }
        set {
            this.lostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public recvRtd rtd {
        get {
            return this.rtdField;
        }
        set {
            this.rtdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rtdSpecified {
        get {
            return this.rtdFieldSpecified;
        }
        set {
            this.rtdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public recvRrs rrs {
        get {
            return this.rrsField;
        }
        set {
            this.rrsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rrsSpecified {
        get {
            return this.rrsFieldSpecified;
        }
        set {
            this.rrsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public recvStart_rtd start_rtd {
        get {
            return this.start_rtdField;
        }
        set {
            this.start_rtdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool start_rtdSpecified {
        get {
            return this.start_rtdFieldSpecified;
        }
        set {
            this.start_rtdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
public enum recvOptional {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
public enum recvRtd {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
public enum recvRrs {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
public enum recvStart_rtd {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class scenario {
    
    private object[] itemsField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CallLengthRepartition", typeof(CallLengthRepartition))]
    [System.Xml.Serialization.XmlElementAttribute("ResponseTimeRepartition", typeof(ResponseTimeRepartition))]
    [System.Xml.Serialization.XmlElementAttribute("label", typeof(label))]
    [System.Xml.Serialization.XmlElementAttribute("pause", typeof(pause))]
    [System.Xml.Serialization.XmlElementAttribute("recv", typeof(recv))]
    [System.Xml.Serialization.XmlElementAttribute("recvCmd", typeof(recvCmd))]
    [System.Xml.Serialization.XmlElementAttribute("send", typeof(send))]
    [System.Xml.Serialization.XmlElementAttribute("sendCmd", typeof(string))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class label {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class recvCmd {
    
    private object[] actionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ereg", typeof(ereg), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("exec", typeof(exec), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("log", typeof(log), IsNullable=false)]
    public object[] action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sipp", IsNullable=false)]
public partial class send {
    
    private object[] actionField;
    
    private string retransField;
    
    private string nextField;
    
    private string testField;
    
    private string lostField;
    
    private sendRtd rtdField;
    
    private bool rtdFieldSpecified;
    
    private sendStart_rtd start_rtdField;
    
    private bool start_rtdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ereg", typeof(ereg), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("exec", typeof(exec), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("log", typeof(log), IsNullable=false)]
    public object[] action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string retrans {
        get {
            return this.retransField;
        }
        set {
            this.retransField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string next {
        get {
            return this.nextField;
        }
        set {
            this.nextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string lost {
        get {
            return this.lostField;
        }
        set {
            this.lostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sendRtd rtd {
        get {
            return this.rtdField;
        }
        set {
            this.rtdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rtdSpecified {
        get {
            return this.rtdFieldSpecified;
        }
        set {
            this.rtdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sendStart_rtd start_rtd {
        get {
            return this.start_rtdField;
        }
        set {
            this.start_rtdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool start_rtdSpecified {
        get {
            return this.start_rtdFieldSpecified;
        }
        set {
            this.start_rtdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
public enum sendRtd {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sipp")]
public enum sendStart_rtd {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}
